version: '3.8'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
      POSTGRES_MULTIPLE_DATABASES: "airflow,noaa"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./create_db.sql:/docker-entrypoint-initdb.d/01_create_db.sql
      - ./init_tables.sql:/docker-entrypoint-initdb.d/02_init_tables.sql
    ports:
      - "5432:5432"
    networks:
      - airflow_network

  airflow-webserver:
    image: apache/airflow:2.9.0
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__FERNET_KEY: ""
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__CORE__TEST_CONNECTION: "enabled"
      AIRFLOW__WEBSERVER__WORKERS: 4
      _AIRFLOW_WWW_USER_USERNAME: airflow_admin
      _AIRFLOW_WWW_USER_PASSWORD: admin
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./entrypoint.sh:/entrypoint.sh
    ports:
      - "8989:8080"
    command: ["bash", "-c", "/entrypoint.sh webserver"]
    networks:
      - airflow_network

  airflow-scheduler:
    image: apache/airflow:2.9.0
    depends_on:
      - postgres
      - airflow-webserver
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__FERNET_KEY: ""
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__CORE__TEST_CONNECTION: "enabled"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    command: scheduler
    networks:
      - airflow_network

  airflow-init:
    image: apache/airflow:2.9.0
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__FERNET_KEY: ""
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__CORE__TEST_CONNECTION: "enabled"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./entrypoint.sh:/entrypoint.sh
    entrypoint: ["bash", "-c", "/entrypoint.sh init"]
    networks:
      - airflow_network

volumes:
  postgres_data:

networks:
  airflow_network: