-- Switch to the 'noaa' database
\c noaa

INSERT INTO dim_datatypes (datatype_id, description) VALUES ('ACMC', 'Average cloudiness midnight to midnight from 30-second ceilometer data');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('ACMH', 'Average cloudiness midnight to midnight from manual observations');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('ACSC', 'Average cloudiness sunrise to sunset from 30-second ceilometer data');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('ACSH', 'Average cloudiness sunrise to sunset from manual observations');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('AWND', 'Average wind speed');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('DAEV', 'Number of days included in the multiday evaporation total (MDEV)');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('DAPR', 'Number of days included in the multiday precipitation total (MDPR)');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('DASF', 'Number of days included in the multiday snow fall total (MDSF) ');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('DATN', 'Number of days included in the multiday minimum temperature (MDTN)');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('DATX', 'Number of days included in the multiday maximum temperature (MDTX)');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('DAWM', 'Number of days included in the multiday wind movement (MDWM)');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('DWPR', 'Number of days with non-zero precipitation included in multiday precipitation total (MDPR)');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('EVAP', 'Evaporation of water from evaporation pan');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('FMTM', 'Time of fastest mile or fastest 1-minute wind');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('FRGB', 'Base of frozen ground layer');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('FRGT', 'Top of frozen ground layer');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('FRTH', 'Thickness of frozen ground layer');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('GAHT', 'Difference between river and gauge height');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('MDEV', 'Multiday evaporation total (use with DAEV)');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('MDPR', 'Multiday precipitation total (use with DAPR and DWPR, if available)');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('MDSF', 'Multiday snowfall total ');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('MDTN', 'Multiday minimum temperature (use with DATN)');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('MDTX', 'Multiday maximum temperature (use with DATX)');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('MDWM', 'Multiday wind movement');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('MNPN', 'Daily minimum temperature of water in an evaporation pan');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('MXPN', 'Daily maximum temperature of water in an evaporation pan');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('PGTM', 'Peak gust time');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('PRCP', 'Precipitation');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('PSUN', 'Daily percent of possible sunshine for the period');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('SN01', 'Minimum soil temperature with unknown cover at 5 cm depth');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('SN02', 'Minimum soil temperature with unknown cover at 10 cm depth');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('SN03', 'Minimum soil temperature with unknown cover at 20 cm depth');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('SN11', 'Minimum soil temperature with grass cover at 5 cm depth');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('SN12', 'Minimum soil temperature with grass cover at 10 cm depth');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('SN13', 'Minimum soil temperature with grass cover at 20 cm depth');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('SN14', 'Minimum soil temperature with grass cover at 50 cm depth');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('SN21', 'Minimum soil temperature with fallow cover at 5 cm depth');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('SN22', 'Minimum soil temperature with fallow cover at 10 cm depth');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('SN23', 'Minimum soil temperature with fallow cover at 20 cm depth');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('SN31', 'Minimum soil temperature with bare ground cover at 5 cm depth');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('SN32', 'Minimum soil temperature with bare ground cover at 10 cm depth');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('SN33', 'Minimum soil temperature with bare ground cover at 20 cm depth');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('SN34', 'Minimum soil temperature with bare ground cover at 50 cm depth');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('SN35', 'Minimum soil temperature with bare ground cover at 100 cm depth');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('SN36', 'Minimum soil temperature with bare ground cover at 150 cm depth');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('SN51', 'Minimum soil temperature with sod cover at 5 cm depth');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('SN52', 'Minimum soil temperature with sod cover at 10 cm depth');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('SN53', 'Minimum soil temperature with sod cover at 20 cm depth');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('SN54', 'Minimum soil temperature with sod cover at 50 cm depth');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('SN55', 'Minimum soil temperature with sod cover at 100 cm depth');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('SN56', 'Minimum soil temperature with sod cover at 150 cm depth');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('SN57', 'Minimum soil temperature with sod cover at 180 cm depth');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('SN61', 'Minimum soil temperature with straw multch cover at 5 cm depth');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('SN72', 'Minimum soil temperature with grass muck cover at 10 cm depth');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('SN81', 'Minimum soil temperature with bare muck cover at 5 cm depth');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('SN82', 'Minimum soil temperature with bare muck cover at 10 cm depth');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('SN83', 'Minimum soil temperature with bare muck cover at 20 cm depth');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('SNOW', 'Snowfall');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('SNWD', 'Snow depth');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('SX01', 'Maximum soil temperature with unknown cover at 5 cm depth');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('SX02', 'Maximum soil temperature with unknown cover at 10 cm depth');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('SX03', 'Maximum soil temperature with unknown cover at 20 cm depth');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('SX11', 'Maximum soil temperature with grass cover at 5 cm depth');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('SX12', 'Maximum soil temperature with grass cover at 10 cm depth');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('SX13', 'Maximum soil temperature with grass cover at 20 cm depth');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('SX14', 'Maximum soil temperature with grass cover at 50 cm depth');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('SX15', 'Maximum soil temperature with grass cover at 100 cm depth');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('SX17', 'Maximum soil temperature with grass cover at 180 cm depth');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('SX21', 'Maximum soil temperature with fallow cover at 5 cm depth');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('SX22', 'Maximum soil temperature with fallow cover at 10 cm depth');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('SX23', 'Maximum soil temperature with fallow cover at 20 cm depth');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('SX31', 'Maximum soil temperature with bare ground cover at 5 cm depth');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('SX32', 'Maximum soil temperature with bare ground cover at 10 cm depth');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('SX33', 'Maximum soil temperature with bare ground cover at 20 cm depth');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('SX34', 'Maximum soil temperature with bare ground cover at 50 cm depth');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('SX35', 'Maximum soil temperature with bare ground cover at 100 cm depth');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('SX36', 'Maximum soil temperature with bare ground cover at 150 cm depth');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('SX51', 'Maximum soil temperature with sod cover at 5 cm depth');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('SX52', 'Maximum soil temperature with sod cover at 10 cm depth');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('SX53', 'Maximum soil temperature with sod cover at 20 cm depth');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('SX54', 'Maximum soil temperature with sod cover at 50 cm depth');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('SX55', 'Maximum soil temperature with sod cover at 100 cm depth');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('SX56', 'Maximum soil temperature with sod cover at 150 cm depth');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('SX57', 'Maximum soil temperature with sod cover at 180 cm depth');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('SX61', 'Maximum soil temperature with straw multch cover at 5 cm depth');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('SX72', 'Maximum soil temperature with grass muck cover at 10 cm depth');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('SX81', 'Maximum soil temperature with bare muck cover at 5 cm depth');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('SX82', 'Maximum soil temperature with bare muck cover at 10 cm depth');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('SX83', 'Maximum soil temperature with bare muck cover at 20 cm depth');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('TAVG', 'Average Temperature.');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('THIC', 'Thickness of ice on water');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('TMAX', 'Maximum temperature');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('TMIN', 'Minimum temperature');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('TOBS', 'Temperature at the time of observation');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('TSUN', 'Total sunshine for the period');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('WDF1', 'Direction of fastest 1-minute wind');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('WDF2', 'Direction of fastest 2-minute wind');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('WDF5', 'Direction of fastest 5-second wind');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('WDFG', 'Direction of peak wind gust');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('WDFI', 'Direction of highest instantaneous wind');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('WDFM', 'Fastest mile wind direction');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('WDMV', 'Total wind movement');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('WESD', 'Water equivalent of snow on the ground');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('WESF', 'Water equivalent of snowfall');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('WSF1', 'Fastest 1-minute wind speed');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('WSF2', 'Fastest 2-minute wind speed');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('WSF5', 'Fastest 5-second wind speed');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('WSFG', 'Peak gust wind speed');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('WSFI', 'Highest instantaneous wind speed');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('WSFM', 'Fastest mile wind speed');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('WT01', 'Fog, ice fog, or freezing fog (may include heavy fog)');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('WT02', 'Heavy fog or heaving freezing fog (not always distinguished from fog)');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('WT03', 'Thunder');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('WT04', 'Ice pellets, sleet, snow pellets, or small hail" ');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('WT05', 'Hail (may include small hail)');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('WT06', 'Glaze or rime ');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('WT07', 'Dust, volcanic ash, blowing dust, blowing sand, or blowing obstruction');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('WT08', 'Smoke or haze ');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('WT09', 'Blowing or drifting snow');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('WT10', 'Tornado, waterspout, or funnel cloud" ');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('WT11', 'High or damaging winds');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('WT12', 'Blowing spray');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('WT13', 'Mist');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('WT14', 'Drizzle');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('WT15', 'Freezing drizzle ');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('WT16', 'Rain (may include freezing rain, drizzle, and freezing drizzle)" ');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('WT17', 'Freezing rain ');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('WT18', 'Snow, snow pellets, snow grains, or ice crystals');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('WT19', 'Unknown source of precipitation ');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('WT21', 'Ground fog ');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('WT22', 'Ice fog or freezing fog');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('WV01', 'Fog, ice fog, or freezing fog (may include heavy fog)');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('WV03', 'Thunder');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('WV07', 'Ash, dust, sand, or other blowing obstruction');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('WV18', 'Snow or ice crystals');
INSERT INTO dim_datatypes (datatype_id, description) VALUES ('WV20', 'Rain or snow shower');
